var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/recruitment/vacancies/[id]/actions/route.js")
R.c("server/chunks/[root-of-the-server]__1jq_zgs._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_04lke6x.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/1oeh_server_app_api_recruitment_vacancies_[id]_actions_route_actions_0ojhwzl.js")
R.m(60502)
module.exports=R.m(60502).exports
