/**
 * Application & vacancy state transition rules (README §42).
 * The backend must reject arbitrary status changes.
 */

const APPLICATION_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['SUBMITTED', 'WITHDRAWN', 'CANCELLED'],
  SUBMITTED: ['UNDER_REVIEW', 'WITHDRAWN', 'CANCELLED'],
  UNDER_REVIEW: ['LONGLISTED', 'INELIGIBLE', 'WITHDRAWN', 'CANCELLED'],
  LONGLISTED: ['SHORTLISTED', 'NOT_SELECTED', 'WITHDRAWN', 'CANCELLED'],
  SHORTLISTED: ['ASSESSMENT_INVITED', 'INTERVIEW_INVITED', 'NOT_SELECTED', 'WITHDRAWN', 'CANCELLED'],
  ASSESSMENT_INVITED: ['ASSESSMENT_COMPLETED', 'NOT_SELECTED', 'WITHDRAWN', 'CANCELLED'],
  ASSESSMENT_COMPLETED: ['INTERVIEW_INVITED', 'NOT_SELECTED', 'WITHDRAWN', 'CANCELLED'],
  INTERVIEW_INVITED: ['INTERVIEW_COMPLETED', 'NOT_SELECTED', 'WITHDRAWN', 'CANCELLED'],
  INTERVIEW_COMPLETED: ['REFERENCE_CHECK', 'NOT_SELECTED', 'WITHDRAWN', 'CANCELLED'],
  REFERENCE_CHECK: ['RECOMMENDED', 'NOT_SELECTED', 'RESERVE', 'WITHDRAWN', 'CANCELLED'],
  RECOMMENDED: ['OFFER_DRAFT', 'NOT_SELECTED', 'RESERVE', 'WITHDRAWN', 'CANCELLED'],
  RESERVE: ['RECOMMENDED', 'NOT_SELECTED', 'CANCELLED'],
  OFFER_DRAFT: ['OFFER_SENT', 'CANCELLED'],
  OFFER_SENT: ['OFFER_ACCEPTED', 'OFFER_DECLINED', 'OFFER_EXPIRED', 'CANCELLED'],
  OFFER_ACCEPTED: ['PREBOARDING', 'CANCELLED'],
  PREBOARDING: ['READY_TO_RESUME', 'CANCELLED'],
  READY_TO_RESUME: ['RESUMED', 'CANCELLED'],
  RESUMED: ['TRANSFERRED_TO_ERP'],
  TRANSFERRED_TO_ERP: [],
  NOT_SELECTED: [],
  INELIGIBLE: [],
  WITHDRAWN: [],
  CANCELLED: [],
}

const VACANCY_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['PENDING_APPROVAL', 'CANCELLED'],
  PENDING_APPROVAL: ['DRAFT', 'SCHEDULED', 'OPEN', 'CANCELLED'],
  SCHEDULED: ['OPEN', 'CANCELLED'],
  OPEN: ['PAUSED', 'CLOSED', 'CANCELLED'],
  PAUSED: ['OPEN', 'CLOSED', 'CANCELLED'],
  CLOSED: ['COMPLETED'],
  COMPLETED: ['ARCHIVED'],
  CANCELLED: [],
  ARCHIVED: [],
}

export function canTransitionApplication(from: string, to: string): boolean {
  if (from === to) return true
  return (APPLICATION_TRANSITIONS[from] ?? []).includes(to)
}

export function canTransitionVacancy(from: string, to: string): boolean {
  if (from === to) return true
  return (VACANCY_TRANSITIONS[from] ?? []).includes(to)
}

/** Statuses the generic recruitment stage command may set. Later workflow
 * outcomes are owned by assessment/interview/reference/selection/offer/
 * preboarding/resumption endpoints that enforce their evidence gates. */
export function isGenericApplicationStage(to: string): boolean {
  return ['UNDER_REVIEW', 'LONGLISTED', 'SHORTLISTED', 'INELIGIBLE', 'CANCELLED'].includes(to)
}

export function allowedApplicationTransitions(from: string): string[] {
  return APPLICATION_TRANSITIONS[from] ?? []
}

export function allowedVacancyTransitions(from: string): string[] {
  return VACANCY_TRANSITIONS[from] ?? []
}

const CANDIDATE_VISIBLE_STATUS: Record<string, string> = {
  DRAFT: 'APPLICATION_DRAFT',
  SUBMITTED: 'APPLICATION_RECEIVED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  LONGLISTED: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  ASSESSMENT_INVITED: 'ASSESSMENT_STAGE',
  ASSESSMENT_COMPLETED: 'ASSESSMENT_STAGE',
  INTERVIEW_INVITED: 'INTERVIEW_STAGE',
  INTERVIEW_COMPLETED: 'INTERVIEW_STAGE',
  REFERENCE_CHECK: 'UNDER_REVIEW',
  RECOMMENDED: 'UNDER_REVIEW',
  RESERVE: 'UNDER_REVIEW',
  OFFER_DRAFT: 'UNDER_REVIEW',
  OFFER_SENT: 'OFFER_SENT',
  OFFER_ACCEPTED: 'PREBOARDING_IN_PROGRESS',
  PREBOARDING: 'PREBOARDING_IN_PROGRESS',
  READY_TO_RESUME: 'READY_TO_RESUME',
  RESUMED: 'RECRUITMENT_COMPLETED',
  TRANSFERRED_TO_ERP: 'RECRUITMENT_COMPLETED',
  INELIGIBLE: 'UNSUCCESSFUL',
  NOT_SELECTED: 'UNSUCCESSFUL',
  OFFER_DECLINED: 'RECRUITMENT_COMPLETED',
  OFFER_EXPIRED: 'RECRUITMENT_COMPLETED',
  WITHDRAWN: 'RECRUITMENT_COMPLETED',
  CANCELLED: 'RECRUITMENT_COMPLETED',
}

export function candidateVisibleStatusForInternal(status: string): string {
  return CANDIDATE_VISIBLE_STATUS[status] || 'UNDER_REVIEW'
}
