var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/recruitment/preboarding/[id]/manage/route.js")
R.c("server/chunks/[root-of-the-server]__176f92v._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_081h-kc.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/1oeh_server_app_api_recruitment_preboarding_[id]_manage_route_actions_1742m63.js")
R.m(49211)
module.exports=R.m(49211).exports
