var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/candidate/profile-items/route.js")
R.c("server/chunks/[root-of-the-server]__0p2nk37._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1_-bm-o.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/_next-internal_server_app_api_candidate_profile-items_route_actions_123p28w.js")
R.m(32681)
module.exports=R.m(32681).exports
