'use client'
import { useState } from 'react'
import Link from 'next/link'

export default function GlobalSearch(){
  const[query,setQuery]=useState('')
  const[data,setData]=useState<any>({applications:[],vacancies:[]})
  const[message,setMessage]=useState('')
  const[busy,setBusy]=useState(false)
  const search=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');const response=await fetch(`/api/recruitment/search?q=${encodeURIComponent(query)}`);const body=await response.json();if(response.ok)setData(body);else setMessage(body.error||'Search failed');setBusy(false)}
  return <div className="space-y-6"><form onSubmit={search} className="flex gap-2"><label htmlFor="global-search" className="sr-only">Search recruitment records</label><input id="global-search" minLength={2} maxLength={100} required value={query} onChange={event=>setQuery(event.target.value)} placeholder="Candidate, email, phone, vacancy, project, department, station, or ERP number" className="min-w-0 flex-1 rounded-xl border border-slate-300 p-3 text-sm"/><button disabled={busy} className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'Searching…':'Search'}</button></form>{message&&<p role="alert" className="text-sm text-rose-700">{message}</p>}<section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Candidates and applications ({data.applications.length})</h2>{data.applications.map((record:any)=><Link key={record.id} href={`/recruitment/applications/${record.id}`} className="mt-3 block rounded-xl border p-3 text-sm hover:border-blue-400"><b>{record.name}</b> — {record.vacancy}<span className="block text-xs text-slate-500">{record.email} · {record.phone||'No phone'} · {record.reference} · {record.department} · {record.dutyStation} · {record.status}{record.erpPersonnelNumber?` · ERP ${record.erpPersonnelNumber}`:''}</span></Link>)}{!data.applications.length&&<p className="mt-2 text-xs text-slate-500">No matching accessible applications.</p>}</section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Vacancies ({data.vacancies.length})</h2>{data.vacancies.map((record:any)=><Link key={record.id} href={`/recruitment/vacancies/${record.id}`} className="mt-3 block rounded-xl border p-3 text-sm hover:border-blue-400"><b>{record.reference} — {record.title}</b><span className="block text-xs text-slate-500">{record.project||'No project'} · {record.department} · {record.dutyStation} · {record.status}</span></Link>)}{!data.vacancies.length&&<p className="mt-2 text-xs text-slate-500">No matching accessible vacancies.</p>}</section></div>
}
