var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/recruitment/candidate-assessments/[id]/answers/route.js")
R.c("server/chunks/[root-of-the-server]__1f3lkp5._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1diwvfd.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/1jng_app_api_recruitment_candidate-assessments_[id]_answers_route_actions_0822gzs.js")
R.m(32854)
module.exports=R.m(32854).exports
