export const BUILTIN_ROLES = [
  { name: 'PUBLIC', description: 'Public visitor' },
  { name: 'CANDIDATE', description: 'Job applicant and preboarding candidate' },
  { name: 'RECRUITMENT_OFFICER', description: 'HR recruitment officer managing vacancies and candidates' },
  {
    name: 'HR_MANAGER',
    description: 'HR manager owning recruitment, preboarding learning, clearance and controlled HR decisions',
  },
  { name: 'HIRING_MANAGER', description: 'Hiring manager reviewing assigned candidates and panels' },
  {
    name: 'BUDGET_HOLDER',
    description: 'Budget holder confirming funding, ceilings and budget lines for staffing requests',
  },
  { name: 'PANEL_MEMBER', description: 'Interview panel scoring member' },
  { name: 'APPROVER', description: 'Executive approver' },
  { name: 'SYSTEM_ADMIN', description: 'System administrator' },
  { name: 'AUDITOR', description: 'Read-only compliance auditor' },
] as const

export const PERMISSION_DEFINITIONS = [
  { code: '*', description: 'Legacy wildcard; not assigned to built-in roles' },
  { code: 'vacancy.create.all', description: 'Create vacancies' },
  { code: 'vacancy.read.all', description: 'Read all vacancies' },
  { code: 'vacancy.read.assigned', description: 'Read vacancies owned by or assigned to the user' },
  { code: 'vacancy.update.all', description: 'Update vacancies' },
  { code: 'application.read.assigned', description: 'Read assigned applications' },
  { code: 'application.read.all', description: 'Read all applications' },
  { code: 'application.stage.change', description: 'Change application stage' },
  { code: 'scorecard.submit', description: 'Submit scorecards' },
  { code: 'scorecard.reopen', description: 'Reopen submitted scorecards with a reason' },
  { code: 'assessment.manage', description: 'Manage assessments' },
  { code: 'interview.manage', description: 'Manage interviews' },
  { code: 'interview.score.assigned', description: 'Score interviews assigned to the user' },
  { code: 'reference.manage', description: 'Manage reference checks' },
  { code: 'offer.manage', description: 'Manage offers' },
  { code: 'preboarding.manage', description: 'Manage preboarding' },
  { code: 'preboarding.clearance', description: 'Issue final preboarding clearance' },
  { code: 'resumption.confirm', description: 'Confirm actual resumption' },
  { code: 'course.manage', description: 'Manage preboarding course content and enrolment as HR' },
  {
    code: 'preboarding.restricted.read',
    description: 'Read restricted bank, pension, medical, accessibility and next-of-kin forms',
  },
  { code: 'erp.transfer', description: 'Record ERP transfer' },
  { code: 'admin.manage', description: 'Administer configuration' },
  { code: 'audit.read', description: 'Read audit logs' },
  { code: 'report.export', description: 'Export recruitment and preboarding reports' },
  { code: 'complaint.manage', description: 'Manage restricted complaints and case records' },
  { code: 'governance.manage', description: 'Manage legal holds, retention and access reviews' },
  { code: 'staffing.request.create', description: 'Raise and edit own staffing requests' },
  { code: 'staffing.request.read.assigned', description: 'Read own or departmental staffing requests' },
  { code: 'staffing.request.read.all', description: 'Read all staffing requests' },
  { code: 'staffing.request.review', description: 'Review and return staffing requests as HR' },
  { code: 'staffing.request.approve', description: 'Approve a staffing request for vacancy preparation' },
  { code: 'funding.confirm', description: 'Confirm or reject funding, ceilings and budget lines' },
  { code: 'funding.read', description: 'Read funding confirmations and financial envelopes' },
  { code: 'offer.financial.confirm', description: 'Confirm offer terms above the approved ceiling' },
  { code: 'longlist.rule.manage', description: 'Define and amend vacancy longlisting rules' },
  { code: 'longlist.run', description: 'Run automatic longlisting over a vacancy' },
  { code: 'longlist.review', description: 'Work the longlisting exception-review queue' },
  { code: 'longlist.override', description: 'Override an automated longlisting outcome with a reason' },
  { code: 'longlist.confirm', description: 'Confirm the final longlist for a vacancy' },
  { code: 'backgroundcheck.manage', description: 'Request and record background and due-diligence checks' },
  { code: 'backgroundcheck.read.restricted', description: 'Read restricted background-check findings' },
  { code: 'signature.sign', description: 'Apply an electronic signature or approval' },
  { code: 'signature.read', description: 'Read the electronic signature register' },
] as const

export const BUILTIN_ROLE_GRANTS: Record<string, readonly string[]> = {
  SYSTEM_ADMIN: ['admin.manage', 'audit.read', 'governance.manage'],
  HR_MANAGER: [
    'vacancy.create.all',
    'vacancy.read.all',
    'vacancy.update.all',
    'application.read.all',
    'application.stage.change',
    'scorecard.submit',
    'scorecard.reopen',
    'assessment.manage',
    'interview.manage',
    'reference.manage',
    'offer.manage',
    'preboarding.manage',
    'preboarding.clearance',
    'resumption.confirm',
    'course.manage',
    'preboarding.restricted.read',
    'erp.transfer',
    'audit.read',
    'report.export',
    'complaint.manage',
    'governance.manage',
    'staffing.request.create',
    'staffing.request.read.all',
    'staffing.request.review',
    'staffing.request.approve',
    'funding.read',
    'longlist.rule.manage',
    'longlist.run',
    'longlist.review',
    'longlist.override',
    'longlist.confirm',
    'backgroundcheck.manage',
    'backgroundcheck.read.restricted',
    'signature.sign',
    'signature.read',
  ],
  RECRUITMENT_OFFICER: [
    'vacancy.create.all',
    'vacancy.read.all',
    'vacancy.update.all',
    'application.read.all',
    'application.stage.change',
    'scorecard.submit',
    'assessment.manage',
    'interview.manage',
    'interview.score.assigned',
    'reference.manage',
    'offer.manage',
    'preboarding.manage',
    'resumption.confirm',
    'erp.transfer',
    'complaint.manage',
    'staffing.request.create',
    'staffing.request.read.all',
    'staffing.request.review',
    'funding.read',
    'longlist.rule.manage',
    'longlist.run',
    'longlist.review',
    'backgroundcheck.manage',
    'backgroundcheck.read.restricted',
    'signature.sign',
    'signature.read',
  ],
  HIRING_MANAGER: [
    'vacancy.read.assigned',
    'application.read.assigned',
    'scorecard.submit',
    'interview.manage',
    'interview.score.assigned',
    'staffing.request.create',
    'staffing.request.read.assigned',
    'signature.sign',
  ],
  BUDGET_HOLDER: [
    'staffing.request.read.assigned',
    'funding.confirm',
    'funding.read',
    'offer.financial.confirm',
    'signature.sign',
  ],
  PANEL_MEMBER: ['application.read.assigned', 'interview.score.assigned', 'signature.sign'],
  APPROVER: ['staffing.request.read.all', 'signature.sign'],
  AUDITOR: [
    'vacancy.read.all',
    'application.read.all',
    'audit.read',
    'report.export',
    'staffing.request.read.all',
    'funding.read',
    'signature.read',
  ],
}

export const LIVE_PERSONA_ACCOUNTS = [
  ['admin@fradfoundation.org', 'SYSTEM_ADMIN'],
  ['hrmanager@fradfoundation.org', 'HR_MANAGER'],
  ['candidate@example.com', 'CANDIDATE'],
  ['recruitment.officer@fradfoundation.org', 'RECRUITMENT_OFFICER'],
  ['hiring.manager@fradfoundation.org', 'HIRING_MANAGER'],
  ['budget.holder@fradfoundation.org', 'BUDGET_HOLDER'],
  ['panel.member@fradfoundation.org', 'PANEL_MEMBER'],
  ['approver@fradfoundation.org', 'APPROVER'],
  ['auditor@fradfoundation.org', 'AUDITOR'],
] as const
