// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/assessment-bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assessment-bank">> = Specific
  const handler = {} as typeof import("../../src/app/admin/assessment-bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/automations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/configuration-releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuration-releases">> = Specific
  const handler = {} as typeof import("../../src/app/admin/configuration-releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/contract-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contract-types">> = Specific
  const handler = {} as typeof import("../../src/app/admin/contract-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses">> = Specific
  const handler = {} as typeof import("../../src/app/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/deletion-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/deletion-requests">> = Specific
  const handler = {} as typeof import("../../src/app/admin/deletion-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/departments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/departments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/departments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/document-requirements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/document-requirements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/document-requirements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/document-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/document-types">> = Specific
  const handler = {} as typeof import("../../src/app/admin/document-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/duty-stations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/duty-stations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/duty-stations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/forms">> = Specific
  const handler = {} as typeof import("../../src/app/admin/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/fraud-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fraud-reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/fraud-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/governance">> = Specific
  const handler = {} as typeof import("../../src/app/admin/governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/interview-questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/interview-questions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/interview-questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/notification-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notification-templates">> = Specific
  const handler = {} as typeof import("../../src/app/admin/notification-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/operating-model/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operating-model">> = Specific
  const handler = {} as typeof import("../../src/app/admin/operating-model/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/policies">> = Specific
  const handler = {} as typeof import("../../src/app/admin/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/preboarding-packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/preboarding-packages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/preboarding-packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../src/app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../src/app/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/scorecards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/scorecards">> = Specific
  const handler = {} as typeof import("../../src/app/admin/scorecards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/system-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system-settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/system-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/templates">> = Specific
  const handler = {} as typeof import("../../src/app/admin/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/vacancy-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/vacancy-categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/vacancy-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/accommodations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/accommodations">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/accommodations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/applications/[id]/receipt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/applications/[id]/receipt">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/applications/[id]/receipt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/applications/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/applications/apply">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/applications/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/applications">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/assessments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/assessments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/complaints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/complaints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/interviews">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/messages">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/offers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/offers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/offers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/offers">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/courses">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/documents">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/forms">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/policies">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/reporting-information/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/reporting-information">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/reporting-information/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/preboarding/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/preboarding/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/preboarding/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/profile/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/profile/documents">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/profile/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/profile/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/profile/education">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/profile/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/profile/employment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/profile/employment">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/profile/employment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/profile/licences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/profile/licences">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/profile/licences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/profile">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/profile/personal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/profile/personal">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/profile/personal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/settings">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/candidate/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidate/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/candidate/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/[reference]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/[reference]">> = Specific
  const handler = {} as typeof import("../../src/app/careers/[reference]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/complaints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/complaints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guidance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guidance">> = Specific
  const handler = {} as typeof import("../../src/app/guidance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/public/reference/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/reference/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/public/reference/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment-faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment-faq">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment-faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment-process/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment-process">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment-process/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/accommodations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/accommodations">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/accommodations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/applications/[id]/handover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/applications/[id]/handover">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/applications/[id]/handover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/applications">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/audit">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/communications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/communications">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/communications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/complaints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/complaints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/insights">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/interviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/interviews">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/interviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/offers">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/operations">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/preboarding/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/preboarding/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/preboarding/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/preboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/preboarding">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/preboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/quality">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/references/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/references">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/references/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/reports">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/search">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/selections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/selections">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/selections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/settings">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/talent-pools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/talent-pools">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/talent-pools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/vacancies/[id]/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/vacancies/[id]/applications">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/vacancies/[id]/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/vacancies/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/vacancies/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/vacancies/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/vacancies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/vacancies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/vacancies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/vacancies/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/vacancies/new">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/vacancies/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/vacancies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/vacancies">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/vacancies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recruitment/work/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruitment/work">> = Specific
  const handler = {} as typeof import("../../src/app/recruitment/work/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/report-fraud/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-fraud">> = Specific
  const handler = {} as typeof import("../../src/app/report-fraud/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/report-recruitment-fraud/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report-recruitment-fraud">> = Specific
  const handler = {} as typeof import("../../src/app/report-recruitment-fraud/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/automations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/automations">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/automations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/configuration-builder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/configuration-builder">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/configuration-builder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/configuration-releases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/configuration-releases">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/configuration-releases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/deletion-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/deletion-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/deletion-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/fraud-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/fraud-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/fraud-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/generic/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/generic">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/generic/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/governance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/governance">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/governance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/operating-model/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/operating-model">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/operating-model/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/download/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/download/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/download/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mfa/challenge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mfa/challenge">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mfa/challenge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mfa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mfa">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mfa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/sso/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sso/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/sso/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/sso/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sso/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/sso/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/interviews/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/interviews/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/interviews/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/accommodations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/accommodations">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/accommodations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/account">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/applications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/applications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/assessments/[id]/answers/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/assessments/[id]/answers/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/assessments/[id]/answers/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/assessments/[id]/answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/assessments/[id]/answers">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/assessments/[id]/answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/assessments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/assessments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/assessments/[id]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/assessments/[id]/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/assessments/[id]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/assessments/[id]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/assessments/[id]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/assessments/[id]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/education/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/education/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/education/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/education/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/education">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/education/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/employment/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/employment/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/employment/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/employment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/employment">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/employment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/interviews/[id]/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/interviews/[id]/respond">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/interviews/[id]/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/licences/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/licences/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/licences/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/licences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/licences">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/licences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/offers/[id]/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/offers/[id]/respond">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/offers/[id]/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/offers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/offers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/offers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/preboarding/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/preboarding/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/preboarding/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/preboarding/confirm-start-date/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/preboarding/confirm-start-date">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/preboarding/confirm-start-date/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/preboarding/courses/[id]/certificate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/preboarding/courses/[id]/certificate">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/preboarding/courses/[id]/certificate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/preboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/preboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/preboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/privacy/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/privacy/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/privacy/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/profile-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/profile-items">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/profile-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/candidate/saved-searches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidate/saved-searches">> = Specific
  const handler = {} as typeof import("../../src/app/api/candidate/saved-searches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/complaints/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/api/complaints/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/process-schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/process-schedules">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/process-schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/fraud-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/fraud-reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/fraud-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/reference/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reference/resolve">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/reference/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/reference/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reference/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/reference/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/vacancies/[reference]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/vacancies/[reference]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/vacancies/[reference]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/vacancies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/vacancies">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/vacancies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/accommodations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/accommodations">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/accommodations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/assign-reviewer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/assign-reviewer">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/assign-reviewer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/conflict/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/conflict">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/conflict/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/documentation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/documentation">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/documentation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/erp-transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/erp-transfer">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/erp-transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/handover-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/handover-summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/handover-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/referees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/referees">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/referees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/resumption/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/resumption">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/resumption/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/[id]/stage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/[id]/stage">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/[id]/stage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/assisted/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/assisted">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/assisted/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/bulk-actions/[id]/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/bulk-actions/[id]/undo">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/bulk-actions/[id]/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/bulk-actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/bulk-actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/bulk-actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/bulk-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/bulk-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/bulk-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/bulk-stage-change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications/bulk-stage-change">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/bulk-stage-change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/approvals">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/assessments/[id]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/assessments/[id]/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/assessments/[id]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/assessments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/assessments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/candidate-assessments/[id]/answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/candidate-assessments/[id]/answers">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/candidate-assessments/[id]/answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/candidate-assessments/[id]/mark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/candidate-assessments/[id]/mark">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/candidate-assessments/[id]/mark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/candidate-assessments/[id]/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/candidate-assessments/[id]/reset">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/candidate-assessments/[id]/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/complaints/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/complaints">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/complaints/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/data-quality/merges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/data-quality/merges">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/data-quality/merges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/eligibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/eligibility">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/eligibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/[id]/confirm-panel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews/[id]/confirm-panel">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/[id]/confirm-panel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/[id]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews/[id]/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/[id]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/[id]/panel/[memberId]/reopen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews/[id]/panel/[memberId]/reopen">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/[id]/panel/[memberId]/reopen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/[id]/panel/[memberId]/resolve-conflict/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews/[id]/panel/[memberId]/resolve-conflict">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/[id]/panel/[memberId]/resolve-conflict/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/[id]/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews/[id]/scores">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/[id]/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/interviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/interviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/interviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/offers/[id]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/offers/[id]/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/offers/[id]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/offers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/offers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/offers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/offers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/offers">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/offers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/preboarding/[id]/manage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/preboarding/[id]/manage">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/preboarding/[id]/manage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/preboarding/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/preboarding/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/preboarding/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/preboarding/clearance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/preboarding/clearance">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/preboarding/clearance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/referees/[id]/send-reminder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/referees/[id]/send-reminder">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/referees/[id]/send-reminder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/referees/[id]/send-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/referees/[id]/send-request">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/referees/[id]/send-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/reference-responses/[id]/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/reference-responses/[id]/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/reference-responses/[id]/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/reports/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/reports/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/reports/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/reports/schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/reports/schedules">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/reports/schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/scorecards/[id]/reopen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/scorecards/[id]/reopen">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/scorecards/[id]/reopen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/scorecards/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/scorecards/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/scorecards/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/scorecards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/scorecards">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/scorecards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/selections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/selections">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/selections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/talent-pools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/talent-pools">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/talent-pools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/vacancies/[id]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/vacancies/[id]/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/vacancies/[id]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/vacancies/[id]/documentation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/vacancies/[id]/documentation">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/vacancies/[id]/documentation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/vacancies/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/vacancies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/vacancies/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/vacancies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/vacancies">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/vacancies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recruitment/work-items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recruitment/work-items/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/recruitment/work-items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
