var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/recruitment/interviews/[id]/scores/route.js")
R.c("server/chunks/[root-of-the-server]__095rwvl._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_12elvep.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/1oeh_server_app_api_recruitment_interviews_[id]_scores_route_actions_0dv_gxm.js")
R.m(53111)
module.exports=R.m(53111).exports
