var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/candidate/preboarding/actions/route.js")
R.c("server/chunks/[root-of-the-server]__1oi-360._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0ojes0q.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/1oeh_server_app_api_candidate_preboarding_actions_route_actions_1h18xuj.js")
R.m(47930)
module.exports=R.m(47930).exports
