var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/generic/route.js")
R.c("server/chunks/[root-of-the-server]__12y6_5y._.js")
R.c("server/chunks/src_lib_validation_ts_0ugplpv._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1s7tk3k.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_1u11086._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_generic_route_actions_19g0ity.js")
R.m(77201)
module.exports=R.m(77201).exports
