var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/preboarding-packages/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n0mt--._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0bk_2_o.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c2joxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1f7o9h7._.js")
R.c("server/chunks/ssr/src_1sjvgxm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0b4ex_-._.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/_1fmrl52._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/[root-of-the-server]__19fhnj5._.js")
R.c("server/chunks/ssr/_0ufc_5g._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_preboarding-packages_page_actions_1e4m3or.js")
R.m(18138)
module.exports=R.m(18138).exports
