var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/candidate/assessments/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_8z3qk._.js")
R.c("server/chunks/ssr/_0ufc_5g._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0o9t3eg.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c2joxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1f7o9h7._.js")
R.c("server/chunks/ssr/src_1sjvgxm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0b4ex_-._.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/_1fmrl52._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/_next-internal_server_app_candidate_assessments_page_actions_0nyeu-t.js")
R.m(19634)
module.exports=R.m(19634).exports
