var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/recruitment/applications/[id]/handover/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__06xsx3i._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1pt7flu.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c2joxc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1f7o9h7._.js")
R.c("server/chunks/ssr/src_1sjvgxm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0b4ex_-._.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/_1fmrl52._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/1oeh_server_app_recruitment_applications_[id]_handover_page_actions_1-u7wko.js")
R.m(86119)
module.exports=R.m(86119).exports
